--- #YAML:1.0
name: File-Type
version: 0.10
license: perl
distribution_type: module
requires:
  File::Slurp: 0.01
  IO::File: 0.01
  Test::More: 0.01
recommends: {}
build_requires: {}
conflicts: {}
provides:
  File::Type:
    file: lib/File/Type.pm
    version: 0.10
  File::Type::Builder:
    file: lib/File/Type/Builder.pm
    version: 0.05
generated_by: Module::Build version 0.19
